### ISSUE TITLE
64-bit support for iOS 8

### ISSUE THREAD

**Issue by onurcaglayan** [showkit/cordova-plugin-showkit#4]
Apple requires to 64-bit support to be able to release a version:

Missing 64-bit support - Beginning on February 1, 2015 new iOS apps submitted to the App Store must include 64-bit support and be built with the iOS 8 SDK. Beginning June 1, 2015 app updates will also need to follow the same requirements. To enable 64-bit in your project, we recommend using the default Xcode build setting of “Standard architectures” to build a single binary with both 32-bit and 64-bit code.

Details:
https://developer.apple.com/news/?id=10202014a

Showkit Plugin needs to be supporting 64-bit otherwise new app cannot go live. 

Thanks!
Onur

**Comment by mark-veenstra** [comment]
@onurcaglayan @akelani 

Correct me if I am wrong, but there is a ShowKit IOS v2.0-RC1 which has arm64 support released, check https://www.showkit.com/releases.

```
v2.0-RC1 --- February 17, 2015
-- Added arm64 support
-- Utilizes iOS 8 VideoToolbox Framework
-- Various performance updates
-- Works with Windows/OS X plugin 2.0
```

Within the plugin there is a directory `src/ios/ShowKit.framework`, maybe it is just replacing this folder with the `ShowKit.framework` folder from the IOS SDK release?

@onurcaglayan Do you have working code with ShowKit and Cordova at this moment? And are you willing / able to share this?

**Comment by onurcaglayan** [comment]
I've just seen that SDK (framework) has been updated, today.
But I guess that we also need updated Cordova Plugin's code (such as ShowKitPlugin.m, ShowKitPlugin.h).
I mean "Cordova plugin for ShowKit" should be updated with v2.0-RC1 SDK as well.

**Comment by onurcaglayan** [comment]
This is the error (30 error in total) message I'm having when I replaced ShowKit.framework :

ld: warning: ignoring file zzz-zzz/Plugins/com.showkit.cordova.showkit/ShowKit.framework/ShowKit, missing required architecture x86_64 in file house-calls/Plugins/com.showkit.cordova.showkit/ShowKit.framework/ShowKit (4 slices)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ShowKit", referenced from:
      objc-class-ref in ShowKitPlugin.o
     (maybe you meant: _OBJC_CLASS_$_ShowKitPlugin)
  "_SHKAudioInputModeKey", referenced from:
      ___33-[ShowKitPlugin toggleMuteAudio:]_block_invoke_2 in ShowKitPlugin.o
  "_SHKAudioInputModeMuted", referenced from:
      ___33-[ShowKitPlugin toggleMuteAudio:]_block_invoke_2 in ShowKitPlugin.o
  "_SHKAudioInputModeRecording", referenced from:
      ___33-[ShowKitPlugin toggleMuteAudio:]_block_invoke_2 in ShowKitPlugin.o
  "_SHKConnectionStatusCallFailed", referenced from:
      -[ShowKitPlugin connectionStateChanged:] in ShowKitPlugin.o
...

Any thoughts?

**Comment by onurcaglayan** [comment]
Latest updates fixed the issue.
